name: reserva_eventos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.3
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  crypto: ^3.0.3
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_reserva_eventos.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_reserva_eventos.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_reserva_eventos.png
